### ISSUE TITLE
Data receiver crashes while waiting for data

### ISSUE THREAD

**Issue by dfialho** [davidfialho14/pico_adapters#1]
While waiting for data the server crashes and the log gives the following traceback:

2016-08-08 18:06:13,136:INFO:Waiting for data...
2016-08-08 18:06:13,139:ERROR:Program will closed due to unexpected error...
Traceback (most recent call last):
  File "../pico_adapters/adapters/aethelometer.py", line 56, in main
    receiver.receive_forever()
  File "/home/pi/collectors/pico_adapters/adapters/data_receiver.py", line 62, in receive_forever
    data = self._receive(connection)
  File "/home/pi/collectors/pico_adapters/adapters/data_receiver.py", line 106, in _receive
    end_index = data.find(b'\r\n')
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by dfialho** [comment]
The issue happened because the cached_data in the data receiver was cleared with an empty string instead of empty bytes.
